# Generated by Django 2.2.10 on 2020-09-11 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeputadoPjb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('uf', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoPjb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField()),
                ('nome', models.TextField()),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pjb.DeputadoPjb')),
            ],
        ),
    ]
