# Generated by Django 2.2.10 on 2020-10-01 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pjb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdicaoPjb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
            options={
                'verbose_name': 'edição PJB',
                'verbose_name_plural': 'edições PJB',
            },
        ),
        migrations.AlterModelOptions(
            name='deputadopjb',
            options={'verbose_name': 'deputado PJB', 'verbose_name_plural': 'deputados PJB'},
        ),
        migrations.AlterModelOptions(
            name='projetopjb',
            options={'verbose_name': 'projeto PJB', 'verbose_name_plural': 'projetos PJB'},
        ),
        migrations.RemoveField(
            model_name='projetopjb',
            name='deputado',
        ),
        migrations.RemoveField(
            model_name='projetopjb',
            name='nome',
        ),
        migrations.AddField(
            model_name='deputadopjb',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deputadopjb',
            name='escola',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deputadopjb',
            name='foto',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deputadopjb',
            name='minibio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deputadopjb',
            name='serie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projetopjb',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='autor', to='pjb.DeputadoPjb'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetopjb',
            name='ementa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projetopjb',
            name='entenda_a_proposta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projetopjb',
            name='relator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relator', to='pjb.DeputadoPjb'),
        ),
        migrations.AddField(
            model_name='projetopjb',
            name='texto_original',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deputadopjb',
            name='nome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deputadopjb',
            name='uf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projetopjb',
            name='numero',
            field=models.TextField(help_text='Numeração completa'),
        ),
        migrations.CreateModel(
            name='ComissaoPjb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, null=True)),
                ('sigla', models.TextField(blank=True, null=True)),
                ('edicao_pjb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pjb.EdicaoPjb')),
                ('integrantes', models.ManyToManyField(blank=True, to='pjb.DeputadoPjb')),
                ('presidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presidente', to='pjb.DeputadoPjb')),
                ('vice_presidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vice_presidente', to='pjb.DeputadoPjb')),
            ],
            options={
                'verbose_name': 'comissão PJB',
                'verbose_name_plural': 'comissões PJB',
            },
        ),
        migrations.AddField(
            model_name='deputadopjb',
            name='edicao_pjb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pjb.EdicaoPjb'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetopjb',
            name='comissoes',
            field=models.ManyToManyField(blank=True, to='pjb.ComissaoPjb'),
        ),
        migrations.AddField(
            model_name='projetopjb',
            name='edicao_pjb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pjb.EdicaoPjb'),
            preserve_default=False,
        ),
    ]
