# Generated by Django 2.2.10 on 2020-10-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjb', '0002_auto_20201001_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputadopjb',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='deputado_pjb_foto/'),
        ),
        migrations.AlterField(
            model_name='projetopjb',
            name='texto_original',
            field=models.FileField(blank=True, null=True, upload_to='projeto_pjb/'),
        ),
    ]
