# Generated by Django 2.2.10 on 2020-12-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjb', '0004_auto_20201007_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educador', models.CharField(max_length=300)),
                ('nome_da_instituicao', models.CharField(max_length=300)),
                ('endereco', models.CharField(max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='escola_foto/')),
            ],
            options={
                'verbose_name': 'escola',
                'verbose_name_plural': 'escolas',
            },
        ),
    ]
