# Generated by Django 2.2.10 on 2021-03-30 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pjb', '0004_auto_20201007_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetopjb',
            name='parecer',
            field=models.FileField(blank=True, null=True, upload_to='parecer/'),
        ),
        migrations.AddField(
            model_name='projetopjb',
            name='situacao',
            field=models.CharField(choices=[('AAC', 'Aguardando apreciação na comissão'), ('APC', 'Aprovado em caráter conclusivo na comissão'), ('RJ', 'Rejeitado'), ('EPF', 'Encaminhado para plenária final'), ('APF', 'Aprovado na plenária final'), ('ADS', 'Aguardando designação de status')], default='ADS', max_length=3),
        ),
        migrations.AlterField(
            model_name='comissaopjb',
            name='presidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comissaopjb_presidente', to='pjb.DeputadoPjb'),
        ),
        migrations.AlterField(
            model_name='comissaopjb',
            name='vice_presidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comissaopjb_vice_presidente', to='pjb.DeputadoPjb'),
        ),
        migrations.CreateModel(
            name='PartidoPjb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, null=True)),
                ('sigla', models.TextField(blank=True, null=True)),
                ('edicao_pjb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pjb.EdicaoPjb')),
                ('integrantes', models.ManyToManyField(blank=True, to='pjb.DeputadoPjb')),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidopjb_lider', to='pjb.DeputadoPjb')),
                ('vice_lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidopjb_vice_lider', to='pjb.DeputadoPjb')),
            ],
            options={
                'verbose_name': 'partido PJB',
                'verbose_name_plural': 'partidos PJB',
            },
        ),
        migrations.CreateModel(
            name='MesaDiretoraPjb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edicao_pjb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pjb.EdicaoPjb')),
                ('presidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesadiretorapjb_presidente', to='pjb.DeputadoPjb')),
                ('primeiro_secretario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesadiretorapjb_primeiro_secretario', to='pjb.DeputadoPjb')),
                ('segundo_secretario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesadiretorapjb_segundo_secretario', to='pjb.DeputadoPjb')),
                ('vice_presidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesadiretorapjb_vice_presidente', to='pjb.DeputadoPjb')),
            ],
            options={
                'verbose_name': 'mesa diretora PJB',
                'verbose_name_plural': 'mesas diretoras PJB',
            },
        ),
    ]
