# Generated by Django 2.2.10 on 2021-03-31 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pjb', '0005_auto_20210330_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partidopjb',
            name='vice_lider',
        ),
        migrations.AddField(
            model_name='partidopjb',
            name='primeiro_vice_lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidopjb_primeiro_vice_lider', to='pjb.DeputadoPjb'),
        ),
        migrations.AddField(
            model_name='partidopjb',
            name='quarto_vice_lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidopjb_quarto_vice_lider', to='pjb.DeputadoPjb'),
        ),
        migrations.AddField(
            model_name='partidopjb',
            name='segundo_vice_lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidopjb_segundo_vice_lider', to='pjb.DeputadoPjb'),
        ),
        migrations.AddField(
            model_name='partidopjb',
            name='terceiro_vice_lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidopjb_terceiro_vice_lider', to='pjb.DeputadoPjb'),
        ),
    ]
