version: '2'

volumes:
  pg_data:
    driver: local
  edemocracia:
    driver: local
  audiencias:
    driver: local
  wikilegis:
    driver: local
  discourse:
    driver: local
  pauta:
    driver: local
  newwikilegis:
    driver: local

services:
  nginx:
    image: nginx
    volumes:
      - ./config/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - edemocracia:/var/labhacker/edemocracia/src/public/
      - wikilegis:/var/labhacker/wikilegis/wikilegis/public/
      - audiencias:/var/labhacker/audiencias/public/
      - discourse:/var/www/discourse
      - pauta:/var/labhacker/pauta-participativa/src/public/
      - newwikilegis:/var/labhacker/new-wikilegis/src/public/
    ports:
      - "50003:80"
    links:
      - edemocracia
    env_file:
      - ./.env

  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
      PGDATA : /var/lib/postgresql/data/
    volumes:
     - pg_data:/var/lib/postgresql/data/
    ports:
     - "5432:5432"

  redis:
    image: redis:alpine

  edemocracia:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - ./src/:/var/labhacker/edemocracia/src
      - edemocracia:/var/labhacker/edemocracia/src/public/:z
      - ./tmpdata/:/tmp/data:z
    command: ./runserver
    links:
      - db
    depends_on:
      - db
    environment:
      BASE_URL_EDEMOCRACIA: /pjb/participe/
      BASE_URL_WIKILEGIS: /pjb/wikilegis/
      BASE_URL_PAUTAS: /pjb/pautaparticipativa/
      BASE_URL_AUDIENCIAS: /pjb/audiencias/
      BASE_URL_DISCOURSE: /pjb/expressao/        
      MEDIA_URL: /pjb/participe/media/
      ADMIN_EMAIL: admin@admin.com
      ADMIN_PASSWORD: 123
      ADMIN_USERNAME: admin
      SITE_NAME:
      SITE_LOGO:
      SITE_URL: http://localhost:8000
      DEBUG: 'False'
      SECRET_KEY:
      RECAPTCHA_SITE_KEY:
      RECAPTCHA_PRIVATE_KEY:
      ALLOWED_HOSTS:
      DATABASE_ENGINE: postgresql_psycopg2
      DATABASE_NAME: edemocracia
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      SOCIAL_AUTH_GOOGLE_OAUTH2_KEY:
      SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET:
      SOCIAL_AUTH_FACEBOOK_KEY:
      SOCIAL_AUTH_FACEBOOK_SECRET:
      SOCIAL_AUTH_CD_KEY:
      SOCIAL_AUTH_CD_SECRET:
      SOCIAL_AUTH_CD_VERIFY_SSL:
      CD_AUTHORIZATION_URL:
      CD_ACCESS_TOKEN_URL:
      CD_METADATA_URL:
      SOCIAL_AUTH_REDIRECT_IS_HTTPS:
      CAMARA_LOGIN: 'False'
      LANGUAGE_CODE:
      TIME_ZONE:
      EMAIL_HOST:
      EMAIL_PORT:
      EMAIL_HOST_USER:
      EMAIL_HOST_PASSWORD:
      EMAIL_USE_TLS:
      EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
      DEFAULT_FROM_EMAIL: '"Portal e-Democracia" <edemocracia@camara.leg.br>'
      STATIC_URL: /pjb/participe/static/
      WIKILEGIS_ENABLED: 'True'
      WIKILEGIS_UPSTREAM: http://wikilegis:8000
      WIKILEGIS_API_URL: '/api/v1/'
      WIKILEGIS_API_KEY: api_key
      AUDIENCIAS_ENABLED: 'True'
      AUDIENCIAS_UPSTREAM: http://audienciasweb:8000/pjb/audiencias
      AUDIENCIAS_API_URL:
      AUDIENCIAS_API_KEY: secret_key
      PAUTAS_ENABLED: 'False'
      PAUTAS_UPSTREAM: http://pauta:8000
      PAUTAS_API_URL:
      PAUTAS_API_KEY: api_key
      DISCOURSE_ENABLED: 'True'
      DISCOURSE_UPSTREAM: http://discourse:8080/pjb/expressao
      DISCOURSE_SSO_SECRET: sso_secret
    env_file:
      - ./.env

  wikilegis:
    image: labhackercd/wikilegis:2.3.0
    command: ./start.sh
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./wikilegis/settings_edemocracia.py:/var/labhacker/wikilegis/wikilegis/wikilegis/settings/settings_edemocracia.py:z
      - wikilegis:/var/labhacker/wikilegis/wikilegis/public/:z
      - ./:/tmp/data:z
    environment:
      ADMIN_PASSWORD: 123
      ADMIN_EMAIL: admin@admin.com
      API_KEY: api_key
      SECRET_KEY: secret_key
      FORCE_SCRIPT_NAME: /pjb/wikilegis
      DEBUG: 'False'
      ALLOWED_HOSTS: '*'
      LOGIN_URL: /pjb/
      LOGIN_REDIRECT_URL: /pjb/
      AUTH_USER_MODEL: accounts.User
      ENABLE_REMOTE_USER: 'True'
      SESSION_COOKIE_NAME: wikilegis_session
      DEFAULT_FROM_EMAIL: '"Portal e-Democracia[Wikilegis]" <edemocracia@camara.leg.br>'
      LANGUAGE_CODE: pt-br
      TIME_ZONE: America/Sao_Paulo
      STATIC_URL: /pjb/wikilegis/static/
      MEDIA_URL: /pjb/wikilegis/media/
      DATABASE_ENGINE: postgresql_psycopg2
      DATABASE_NAME: wikilegis
      DATABASE_PASSWORD: root
      DATABASE_USER: root
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      BASE_URL_EDEMOCRACIA: /pjb/participe/
    env_file:
      - ./.env
    expose:
      - "8000"

  audienciasweb:
    image: labhackercd/audiencias-publicas:3.4.4
    command: ./start-web.sh
    restart: on-failure
    links:
      - db
      - redis
    volumes:
      - audiencias:/var/labhacker/audiencias/public/:z
      - ./src/templates/components/edem-navigation.html:/var/labhacker/audiencias/templates/components/edem-navigation.html:z
      - ./audiencias/settings.py:/var/labhacker/audiencias/audiencias_publicas/settings.py:z
      - ./audiencias/audiencias.conf:/etc/nginx/conf.d/audiencias.conf:z
      - ./tmpdata/:/tmp/data:z
    environment:
      BASE_URL_EDEMOCRACIA: /pjb/participe/
      URL_PREFIX: pjb/audiencias
      ADMIN_PASSWORD: 123
      ADMIN_EMAIL: admin@admin.com
      ADMIN_USERNAME: admin
      EMAIL_HOST: ''
      EMAIL_HOST_USER: ''
      EMAIL_HOST_PASSWORD: ''
      EMAIL_PORT: 25
      EMAIL_USE_TLS: 'False'
      DEFAULT_FROM_EMAIL: '"Portal e-Democracia[audiencias]" <edemocracia@camara.leg.br>'
      NOTIFICATION_EMAIL_LIST: edemocracia@camara.leg.br,portalconteudo.lista@camara.leg.br
      DJANGO_SECRET_KEY: secret_key
      RECAPTCHA_SITE_KEY:
      DEBUG: 'False'
      CAMARA_LOGIN: 'False'
      ENABLE_REMOTE_USER: 'True'
      FORCE_SCRIPT_NAME: /pjb/audiencias
      STATIC_URL: /pjb/audiencias/static/
      SESSION_COOKIE_NAME: audiencias_session
      LOGIN_URL: /pjb/home
      LOGIN_REDIRECT_URL: /pjb/home
      LOGOUT_REDIRECT_URL: /pjb/home
      ALLOWED_HOSTS: '*'
      GOOGLE_ANALYTICS_ID: ''
      OLARK_ID: ''
      DATABASE_ENGINE: postgresql_psycopg2
      DATABASE_NAME: audiencias
      DATABASE_PASSWORD: root
      DATABASE_USER: root
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      REDIS_SERVER: redis
      WEBSERVICE_URL: 
      COMPRESS_OFFLINE: 'True'
      WORDS_BLACK_LIST: 'merda,cu,cuzao,cuzona,cusao,cusona,bunda,fodido,fodida,foda,foder,fodedor,fudido,fudida,fuder,chupa,chupada,chupador,chupadora,boquete,boqueteira,boquetera,boketeira,boketera,xupa,xupada,xupador,xupadora,pauduro,pauzudo,xoxota,chochota,buceta,boceta,busseta,bosseta,cacete,cassete,caceta,kacete,kassete,caralho,karalho,caraleo,pinto,pica,rola,roludo,gozado,gozada,goso,gosa,gosado,gosado,puta,puto,putinho,putinha,putona,putana,putaria,grelo,grelinho,filhodaputa,filhosdaputa,puta,fdps,siririca,punheta,trepar,trepada,trepadeira,caralho,caralhu,karalho,karalhu,tomarnocu,tomanocu,vadia,bosta,quenga,rabo,bolsa,cuzinho,piroca,pqp,puta que pariu,porra,carai,cú,viado,fdp,vtnc,corno,bicha,bixa,viado,viadinho,pederasta,filho da puta,bundao,bundão,filho de uma egua,filho de uma égua,achacador,achacadora,achacadores,achacar,babaca,bucetas,cagar,cagaram,cambada,caráleo,corja,cornão,covarde,covardes,cretino,cus,cús,cusão,cuzão,cuzinho,cuzona,danar,desgraça,drosoba,enrabar,escória,escroto,escrotas,escrotos,fodão,fodona,fudendo,fuder,idiota,imundo,imundos,ku,kú,lascar,merdas,patifaria,pilantra,pilantragem,pilantras,poha,porcaria,putas,putos,sacanagem,safadeza,safado,safados,salafrário,salafrários,vagabundagem,vagabundo,vagabundos,veadinho,veadinhos'
    env_file:
      - ./.env
    expose:
      - "8000"
    depends_on:
      - db
      - redis

  audienciasworker:
    image: labhackercd/audiencias-publicas:3.4.4
    command: ./start-worker.sh
    links:
      - redis
      - db
    volumes:
      - audiencias:/var/labhacker/audiencias/public/:z
      - ./config/etc/nginx/conf.d/audiencias.conf:/etc/nginx/conf.d/audiencias.conf:z
      - ./src/templates/components/edem-navigation.html:/var/labhacker/audiencias/templates/components/edem-navigation.html:z
      - ./audiencias/settings.py:/var/labhacker/audiencias/audiencias_publicas/settings.py:z
      - ./tmpdata/:/tmp/data:z
    environment:
      BASE_URL_EDEMOCRACIA: /pjb/participe/
      URL_PREFIX: pjb/audiencias
      ADMIN_PASSWORD: 123
      ADMIN_EMAIL: admin@admin.com
      ADMIN_USERNAME: admin
      EMAIL_HOST: ''
      EMAIL_HOST_USER: ''
      EMAIL_HOST_PASSWORD: ''
      EMAIL_PORT: 25
      EMAIL_USE_TLS: 'False'
      DEFAULT_FROM_EMAIL: '"Portal e-Democracia[audiencias]" <edemocracia@camara.leg.br>'
      NOTIFICATION_EMAIL_LIST: edemocracia@camara.leg.br,portalconteudo.lista@camara.leg.br
      DJANGO_SECRET_KEY: secret_key
      RECAPTCHA_SITE_KEY:
      DEBUG: 'False'
      CAMARA_LOGIN: 'False'
      ENABLE_REMOTE_USER: 'True'
      FORCE_SCRIPT_NAME: /pjb/audiencias
      STATIC_URL: /pjb/audiencias/static/
      SESSION_COOKIE_NAME: audiencias_session
      LOGIN_URL: /pjb/home
      LOGIN_REDIRECT_URL: /pjb/home
      LOGOUT_REDIRECT_URL: /pjb/home
      ALLOWED_HOSTS: '*'
      GOOGLE_ANALYTICS_ID: ''
      OLARK_ID: ''
      DATABASE_ENGINE: postgresql_psycopg2
      DATABASE_NAME: audiencias
      DATABASE_PASSWORD: root
      DATABASE_USER: root
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      REDIS_SERVER: redis
      WEBSERVICE_URL: 
      COMPRESS_OFFLINE: 'True'
      WORDS_BLACK_LIST: 'merda,cu,cuzao,cuzona,cusao,cusona,bunda,fodido,fodida,foda,foder,fodedor,fudido,fudida,fuder,chupa,chupada,chupador,chupadora,boquete,boqueteira,boquetera,boketeira,boketera,xupa,xupada,xupador,xupadora,pauduro,pauzudo,xoxota,chochota,buceta,boceta,busseta,bosseta,cacete,cassete,caceta,kacete,kassete,caralho,karalho,caraleo,pinto,pica,rola,roludo,gozado,gozada,goso,gosa,gosado,gosado,puta,puto,putinho,putinha,putona,putana,putaria,grelo,grelinho,filhodaputa,filhosdaputa,puta,fdps,siririca,punheta,trepar,trepada,trepadeira,caralho,caralhu,karalho,karalhu,tomarnocu,tomanocu,vadia,bosta,quenga,rabo,bolsa,cuzinho,piroca,pqp,puta que pariu,porra,carai,cú,viado,fdp,vtnc,corno,bicha,bixa,viado,viadinho,pederasta,filho da puta,bundao,bundão,filho de uma egua,filho de uma égua,achacador,achacadora,achacadores,achacar,babaca,bucetas,cagar,cagaram,cambada,caráleo,corja,cornão,covarde,covardes,cretino,cus,cús,cusão,cuzão,cuzinho,cuzona,danar,desgraça,drosoba,enrabar,escória,escroto,escrotas,escrotos,fodão,fodona,fudendo,fuder,idiota,imundo,imundos,ku,kú,lascar,merdas,patifaria,pilantra,pilantragem,pilantras,poha,porcaria,putas,putos,sacanagem,safadeza,safado,safados,salafrário,salafrários,vagabundagem,vagabundo,vagabundos,veadinho,veadinhos'
    env_file:
      - ./.env
    volumes:
      - audiencias:/var/labhacker/audiencias/public/:z
      - ./:/tmp/data:z
    depends_on:
      - 'audienciasweb'

  pauta:
    image: labhackercd/pauta-participativa:dev
    command: ./start.sh
    volumes:
      - pauta:/var/labhacker/pauta-participativa/src/public/:z
      - ./:/tmp/data:z
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      BASE_URL_EDEMOCRACIA: /pjb/participe/
      SECRET_KEY:
      API_KEY: api_key
      RECAPTCHA_SITE_KEY:
      RECAPTCHA_PRIVATE_KEY:
      FORCE_SCRIPT_NAME: /pautaparticipativa
      DEBUG: 'False'
      ALLOWED_HOSTS: '*'
      DATABASE_ENGINE: postgresql_psycopg2
      DATABASE_NAME: pauta
      DATABASE_PASSWORD: root
      DATABASE_USER: root
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      ENABLE_REMOTE_USER: 'True'
      SESSION_COOKIE_NAME: pautas_session
      EMAIL_HOST:
      EMAIL_PORT:
      EMAIL_HOST_USER:
      EMAIL_HOST_PASSWORD:
      EMAIL_USE_TLS:
      DEFAULT_FROM_EMAIL: '"Portal e-Democracia[pautaparticipativa]" <edemocracia@camara.leg.br>'
      STATIC_URL: '/pautaparticipativa/static/'
    env_file:
      - ./.env

  discourse:
    image: labhackercd/discourse-docker:2.0.20180703
    command: ./start-web.sh
    volumes:
      - discourse:/var/www/discourse
      - ./:/tmp/edemocracia
    expose:
      - "8080"
    depends_on:
      - db
      - redis
    environment:
      BASE_URL_EDEMOCRACIA: /pjb/participe/
      ADMIN_EMAIL: 'admin@admin.com'
      ADMIN_PASSWORD: '123'
      ADMIN_USERNAME: 'admin'
      RAILS_ENV: 'production'
      DISCOURSE_DB_HOST: db
      DISCOURSE_DB_PORT: '5432'
      DISCOURSE_DB_NAME: 'discourse'
      DISCOURSE_DB_USERNAME: 'root'
      DISCOURSE_DB_PASSWORD: 'root'
      DISCOURSE_HOSTNAME: 'localhost'
      DISCOURSE_SMTP_ADDRESS:
      DISCOURSE_SMTP_PORT: 587
      DISCOURSE_SMTP_USER_NAME:
      DISCOURSE_SMTP_PASSWORD:
      DISCOURSE_DEVELOPER_EMAILS:
      DISCOURSE_REDIS_HOST: 'redis'
      DISCOURSE_REDIS_PORT: 6379
      DISCOURSE_RELATIVE_URL_ROOT: '/pjb/expressao'
      DISCOURSE_CONTACT_EMAIL:
      DISCOURSE_CONTACT_URL: 'localhost'
      DISCOURSE_NOTIFICATION_EMAIL: 'noreply@dicourse.org'
      DISCOURSE_SSO_URL: 'http:\/\/127.0.0.1:8000'
      DISCOURSE_SSO_SECRET: 'sso_secret'
      DISCOURSE_FORCE_HOSTNAME: ''
    env_file:
      - ./.env

